#!/usr/bin/env bash
# This module is used to run a Python module in the Global Village environment
# where Infrastucture/lib must be on the PYTHONPATH to ensure that the correct
# Global Village modules are found at run time. This script can run in any
# directory. It assumes that the library location has been set in the
# environment variable gvSOURCELIB which will be prepended to the standard
# PYTHONPATH environment variable to ensure that the Global Village development
# libraries are available when a Python script is run from the command line.
# It does three things:
#     1. Sets up the appropriate Python virtual environment.
#     2. Adds the Global Village development environment library to the
#        PYTHONPATH.
#     3. Runs the Python program.
#     4. Restores the previous environment.

